# Dockerfile.dev
FROM python:3.14

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

ARG UID
ARG GID
ARG USER

RUN pip install --no-cache-dir uv

RUN \
  addgroup --gid ${GID} appgroup || true \
  && adduser --uid ${UID} --gid ${GID} --disabled-password --gecos "" ${USER}
USER ${USER}

WORKDIR /app
RUN chown ${USER}:appgroup /app

# Install only dependencies
COPY --chown=${USER}:appgroup pyproject.toml uv.lock* *.whl ./
RUN \
  python -m venv --prompt '.' .venv \
  && uv sync --active --frozen --no-install-project --group dev --group test

# Install project
COPY --chown=${USER}:appgroup . .
RUN uv sync --frozen

EXPOSE 2300

CMD ["sleep", "infinity"]
